SecureApiGateway/secure-api-gateway-ob-uk-fidc-initializer

main.go
platform/authenticate.go

Use environment variable to get the am user.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/issues/10

remove hardcoded amadmin username

---

main.go

`CONFIG_DIRECTORY_PATH ` has been replaced with `MANAGED_OBJECTS_DIRECTORY_PATH `.
The morning build failed this morning due to the reference to the redundant config
https://g.codefresh.io/build/60a3574d13dcb14366bee564?step=ig&tab=output&logs=terminal

remove reference to a redundant config

---

.github/workflows/pr.yml
Dockerfile

Fix failure in the way the go binary is build in github actions.
There was a strange error in the morning build: https://g.codefresh.io/build/60c9ad5da876e95a218ebe31?step=ig&tab=output&logs=terminal
Tracked it down to a dynamic link failure described [here](https://stackoverflow.com/a/66974607).

build develop container

---

_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/cronjob.yaml

Change restart policy to `OnFailure`. The documentation suggests that `Always` is supported for `v1beta1` but this isnt the case.
Also add a `successfulJobsHistoryLimit` of 1 to reduce the namespace noise
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/issues/25

restartPolicy to OnFailure

---

_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/cronjob.yaml

The default config created by the CDK deployment is `FQDN` not `IAM_FQDN`.
`IAM_FQDN` was added as part of the "IG" way of deploying the configurator. it is no longer relevant.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/issues/25

Change cm key to FQDN

---

am/oauth2-test.json
am/oauth2.go
am/oauth2_test.go
am/oauth2models.go
am/remote-consent-example.json
am/serviceaccount_test.go

**Changes** 
- Consent Request signing algorithm set to PS256 instead of HS256
- Public key selector set to JWTs instead of JWKs_URI
- Json Web Key set with the content of https://obdemo.dev.forgerock.financial/jwkms/apiclient/jwks
**Issue**
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/208

208: CDK Remote consent configuration fix

---

.gitignore
am/alpha.go
am/alpha_test.go
am/client.go
am/idm.go
am/oauth2.go
am/policy.go
am/serviceaccount.go
am/system_clients.go
common/error.go
mocks/am/RestReaderWriter.go
platform/authenticate.go

- Added pair return on the rest client to catch the http status
- Improved the errors with the http status
- Added a condicional in exist methods to check the http status to check if the object exist (false when 404 is returned)
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/217

217: CDK service users initialisation fix

---

config/defaults/secure-open-banking/oauth2provider-update.json

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/255
I have added the endpoints for each environment in the Acceptable Audience Values field from the OAuth2 Provider.
`
"allowedAudienceValues": [
"https://obdemo.dev.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
"https://obdemo.nightly.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
"https://obdemo.andra-racovita.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
"https://obdemo.mariantiris.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
"https://obdemo.christian-brindley.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token", …

Add the endpoints for each env in the acceptable audience of the OAuth2Provider

---

config/defaults/secure-open-banking/create-base-url-source.json
config/defaults/secure-open-banking/oauth2provider-update.json
main.go
pkg/securebanking/oauth2.go
pkg/securebanking/oauth2_test.go

The aim here is to get a working flow that is FAPI compliant. We can't
do that as yet, but this moves us to a place were at least we can get
flows working using postman. We are now in a position where the URI on
which the OAuth2 well_know response is obtained matches the issuer url
within the response. To do this we have configured the OAuth2Provider to
accept obdemo.<namespace>.forgerock.financial as an Acceptable Audience
Value. This is all good.
The current issue is that the authorize endpoint must be accessed on the
iam.<namespace> domain, but the FAPI conformance suite uses the issuer
value from the well_known namespace as the audience in the request jwt.
This is now the obdemo.<namespace> domain. :-( We don't have an easy way
to fix this.
Issue: …

260: Fix OAuth FAPI issues

---

config/defaults/secure-open-banking/managed-objects/domesticScheduledPaymentIntent.json

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/250
Create the schema for the Domestic Scheduled Payment Intent following the [OBDomesticScheduled2](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-scheduled-payment-consents.html#domestic-scheduled-payment-consent---response) object.
The file containing the implementation is: domesticScheduledPaymentIntent.json
For now, the Charges property is added with the **type: String**. In the [issue #241](https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/241), we keep track of the Charge property not being implemented according to the specifications.

Create the manage object for Domestic Scheduled Payment Intent

---

config/defaults/secure-open-banking/managed-objects/domesticPaymentIntent.json
config/defaults/secure-open-banking/pisp-policy.json
config/defaults/secure-open-banking/policy-evaluation-script.js

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/297
- Add in the Domestic Payment Intent managed object the filed accountId for the DebtorAccount. 
- Updated the policy to accept request from the funds-confirmation endpoint
- Upgrade policy evaluation script to support Domestic Scheduled payment intent. Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/277

Add AccountId in the DebtorAccount. Update policy script

---

config/defaults/secure-open-banking/create-policy-service-user.json
config/viper/viper-default-configuration.yaml
pkg/securebanking/policy.go
pkg/types/configuration.go

create-policy-service-user.json uses hardcoded values. It needs to use variables
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/345

Templated hardcoded values and use umarshal function

---

config/viper/viper-default-configuration.yaml

- Added ig_audience_fqdns for `frlaura-jianu` and `dbadham-fr`
- Deleted `joycegilding-forgerock` audience.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/353

353: Setup SBAT developer environment

---

config/defaults/secure-open-banking/managed-objects/domesticStandingOrderIntent.json
config/defaults/secure-open-banking/policy-evaluation-script.js

- `domesticStandingOrderPaymentIntent` renamed to `domesticStandingOrderIntent`
- Policy script update to use the proper intent name
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/354

354: update standing order intent name

---

_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/cronjob-secret.yaml
_infra/helm/securebanking-openbanking-uk-fidc-initializer/values.yaml

Currently, the cronjob-secret is being created in the dev namespace (default value) for the nightly environment (because we are not overriding the value).
I think that we can simply remove the environment.namespace value and allow Argo CD to default the namespace to that of the application. i.e. All objects for the nightly application will be placed in the nightly namespace.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/441

441: Removing environment.namespace value

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob-secret.yaml

Making the cronjob-secret.yaml definition consistent for both helm charts wrt allowing the namespace to be set based on the argo installation.
See PR: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/pull/95
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/441

441: Removing explicitly setting metadata.namespace

---

config/defaults/secure-open-banking/policy-evaluation-script.js

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/505
Updated the policy script to support the **Consumed** status.

505: Accept Consumed status in the policy script

---

Dockerfile
_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
_infra/helm/securebanking-openbanking-uk-iam-initializer/values.yaml

So that we can deploy images built for a PR when a PR is pushed.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/276

276: Allow argo to override image tag

---

config/defaults/secure-open-banking/managed-objects/accountAccessIntent.json
config/defaults/secure-open-banking/policy-evaluation-script.js

- New structure adds OBIntentObject field, which is an object that matches the OB API type OBReadConsentResponse1
- OBVersion and OBIntentObjectType metadata fields which represent the OB API version used to create the intent and the OB Schema type of the intent i.e. OBReadConsentResponse1 in this case.
- Made OBIntentObject.Data.ConsentId and OBIntentObject.Data.Status fields mandatory
- Updating policy-evaluation-script.js to query this new structure from IDM
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/535

535: Updating accountAccessIntent IDM object structure

---

config/defaults/secure-open-banking/managed-objects/domesticPaymentIntent.json
config/defaults/secure-open-banking/managed-objects/domesticScheduledPaymentIntent.json
config/defaults/secure-open-banking/managed-objects/domesticStandingOrdersIntent.json
config/defaults/secure-open-banking/managed-objects/internationalPaymentIntent.json
config/defaults/secure-open-banking/managed-objects/internationalScheduledPaymentIntent.json
config/defaults/secure-open-banking/managed-objects/internationalStandingOrdersIntent.json
config/defaults/secure-open-banking/policy-evaluation-script.js

- Updating payment intent IDM schema to contain OBVersion, OBIntentType and OBIntentObject fields
- OBIntentObject field now contains the OB consent response object
- Moved custom field: /Data/Initiation/DebtorAccount/AccountId to /AccountId (top level field)
- Updated policy script to be compatible with these changes
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/517

517 payment intent schema restructuring

---

config/defaults/secure-open-banking/managed-objects/filePaymentsIntent.json

- Added `FileContent` field to store the file content
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/589

589: update IDM intent file payments intent to store the file content

---

.github/workflows/pr.yml
_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml

This is necessary because if we set AM to properly use the IG_FQDN then we will need to use IG_FQDN to do some AM config templating, for example the issuer of the access_tokens will now be the IG_FQDN. THis is the cause of issue 615.
Also added to the pr workflow so that when an initialise PR is pushed the initialiser (with PR tag) gets deployed to the developers dev env.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/615

615: Give initialiser templating access to the IG FQDN

---

config/defaults/secure-open-banking/oauth2provider-update.json

Fapi spec
(https://openid.net/specs/openid-financial-api-part-2-1_0.html#algorithm-considerations) states that;
8.6.  Algorithm considerations
For JWS, both clients and authorization servers
shall use PS256 or ES256 algorithms;
should not use algorithms that use RSASSA-PKCS1-v1_5 (e.g. RS256); and
shall not use none.
This commit changes the OAuth2Provider config that gets pushed into the Alpha realm to that only PS256 or ES256 are offered.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/622

622: Restrict allowed OAuth2 signing algos to to FAPI compliant

---

config/defaults/secure-open-banking/oauth2provider-update.json

Ideally we would be able to apply a default FAPI config, and then an 'overlay' for OB specifics or customer specifics etc.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/622

622: OB Spec states only PS256 for signing algos

---

config/defaults/secure-open-banking/managed-objects/apiClient.json

There is no requirement in the spec that an ssa needs to be unique, multiple apiClients should be able to reference the same ssa.
In our current environments this is the case, as we have a bug where the ssa field is not being set. In order to fix that bug we need to disable the unique constraint.
Also doing some cleanup to make the id, name, oauth2ClientId and ssa required fields.
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/621

621: Removing the unique constraint from apiClient.ssa field

---

config/defaults/secure-open-banking/oauth2provider-update.json
config/viper/viper-default-configuration.yaml
pkg/securebanking/oauth2.go

We previously had allowed audience values for all environments in the OAuth2Provider config. Now we can template config pushed to a specific CDK to have only the required allowed audience value.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/259

259: Remove un-necessary allowed audience values

---

config/defaults/secure-open-banking/create-validation-service.json
main.go
pkg/securebanking/validation_service.go

The Validation Service is used to validate that supplied redirect urls are to valid destinations. The initial configuration allows redirects to any AM url and to the IG /am route.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/658

658: Creating Validation Service in AM

---

config/defaults/secure-open-banking/cors-login-ui.json

After updating to AM 7.2.0, CORS filter was denying our requests.
In the AM logs we could see: "CORS Fail - Pre-flight request contained the Access-Control-Request-Headers header with an invalid value 'x-forgerock-transactionid'"
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/629

629: Adding x-forgerock-transactionid header to cors accept list

---

_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/configmap.yaml
_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/cronjob.yaml
_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
config/defaults/secure-open-banking/global-services-platform.json
main.go
pkg/securebanking/cors_service.go
pkg/securebanking/crest_resource_creator.go
pkg/securebanking/platform_service.go
pkg/securebanking/validation_service.go

The Cookie domain needs to be configured in order for the cookie to be sent to IG when we are using it to reverse proxy AM.
- Cookie domain is configured via the Platform Global Service
- Cookie domain is configured to be the BASE_FQDN of the environment e.g. dev.forgerock.financial for dev env
- Extracted common func to create or update resources using AM CREST API, using this for cors and validation service creation as well
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/667

667: Configuring AM cookie domain

---

config/defaults/secure-open-banking/oauth2provider-update.json
pkg/securebanking/oauth2.go
pkg/types/oauth2models.go

This is required to pass the FAPI1-Advanced conformance tests
Issue: https://github.com/secureapigateway/secureapigateway/issues/676

676: Ensure request object has exp and nbf claims

---

config/defaults/secure-open-banking/oauth2provider-update.json
pkg/types/oauth2models.go

Set the maxDifferenceBetweenRequestObjectNbfAndExp to 60 to pass FAPI Advanced Part 1 Conformance Tests
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/676

676: Add AM OAuth2Provider config

---

config/defaults/secure-open-banking/oauth2provider-update.json
config/viper/viper-default-configuration.yaml
main.go
pkg/securebanking/crest_resource_creator.go
pkg/securebanking/google_secret_stores.go
pkg/securebanking/google_secret_stores_test.go
pkg/types/configuration.go
pkg/types/oauth2models.go

This change enables the OAuth2 Provider in AM to do tls_client_auth when TLS is being terminated by a service running in front of the AM instance, in this case by nginx. AM will inspect the configured header for the client's TLS cert and do the authentication checks based on this.
Configuring the Google Secrets Manager to store the trusted CA certs which auth requests will be tested against.
Summary of changes:
- Updating OAuth2 Provider configuration
- Adding new viper config: "TLS.CLIENT_CERT_HEADER_NAME"
- Setting the default configuration to use ssl-client-cert, this is the header that nginx uses to expose the client cert to downstream systems
- Configuring Google Secrets Manager in AM
- Adding GOOGLE_SECRET_STORES block to the config, this describes the secret stores that we wish to …

694: Configuring AM for tls_client_auth

---

config/viper/viper-default-configuration.yaml

The Google Secrets Store cannot be accessed until we complete some devops tasks to setup service accounts to access the secrets. This can be uncommented when: https://github.com/SecureApiGateway/SecureApiGateway/issues/703 is implemented.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/694

694: Disabling creating the Google Secrets Store

---

pkg/securebanking/policy.go

FIDC IDM default user managed objects use a different naming pattern _user Eg:alpha_user
To allow the creation of the SBAT Policy Service User we need to adapt the path so that it uses the configured realm name when targeting the managed object for user creation.
I have tested the change and the Policy Service User is being created.
Checked in the application and also got this in the logs:
"caller":"securebanking/policy.go:36","msg":"Policy Service User","statusCode":201

fix policy service user creation

---

config/defaults/secure-open-banking/policy-evaluation-script.js

When the policy script calls AM and IDM, it now uses the IDENTITY_PLATFORM_FQDN configuration and https.
This will work for both CDK and FIDC environments. The previous setup would only work for CDK (making use of CDK deployed k8s services)
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/304

304: Using IdentityPlatformFQDN in policy script

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
config/viper/viper-default-configuration.yaml
main.go
pkg/securebanking/authentication_config.go
pkg/types/configuration.go

- Adding new configuration item: IDENTITY.DEFAULT_USER_AUTHENTICATION_SERVICE
- Updated the default viper configuration to set `ldapService` which is the default for CDK environments 
- Adding function to configure the realm default user auth service using this config value
- Created PR to override the configuration to `PasswordGrant` for the nightly environment which is a FIDC deployment.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/718

718: Configure the realm default user authentication service

---

.config-git-ref
_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
main.go
pkg/securebanking/google_secret_stores.go
pkg/types/configuration.go
pkg/types/secrets.go

Refactoring to only support creating a single Google Secret Store, there is no use case for needing multiple and FIDC environments only allow a single one.
Changing the logic to only create the secret store for CDK environments, as FIDC come pre-configured with a secret store which cannot be modified.
For CDK & FIDC envs, mapping secrets to the store is supported. Currently only: `am.services.oauth2.tls.client.cert.authentication` can be mapped.
https://github.com/SecureApiGateway/SecureApiGateway/issues/694

694: Configure GoogleSecretStore for CDK environments only.

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/694

694: Fix typo in env var name: IDENTITY.GOOGLE_SECRET_STORE_NAME

---

README.md
_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
pkg/types/configuration.go

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/793

793: Removing reference to RCS_UI_FQDN config map key, as it is now not used

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml

The values were previously not being configured, we were relying on the default values in the viper config to match those in the configmap. The values have now been migrated to secrets, these secrets are being mounted as env vars and are updating the viper config.
In future, if we wish to change the secret values i.e. randomly generate them, IG and the Initializer will now use consistent values.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/784

784: Updating helm chart to make use of the IG_ secrets defined in openig-secrets-env secret

---

config/defaults/secure-open-banking/managed-objects/apiClient.json

Adding deleted field to apiClient, this field is mandatory and is defaulted to false.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/614

614: Adding deleted field to apiClient

---

pkg/securebanking/rcs_jwks_test.go

This test is useful in order to manually convert an RCS PEM into a JWKS.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/904

904: Adding a unit test that can be used to generate a JWKS for the RCS key data

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/readme.md
_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
_infra/helm/securebanking-openbanking-uk-iam-initializer/values.yaml

Remove image override option, and use a default of appVersion if an deployment.image.tag value is not provided (SBAT will now provide this so that the latest image is deployed, and we'll want to not provide the value in relenvs so that the appVersion is used)
Remove unwanted values from values.yaml
Order alphabetically in values.yaml
Standardise values.yaml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/939

939 standardise helm charts

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
_infra/helm/securebanking-openbanking-uk-iam-initializer/values.yaml

Only install the cronjob if the value enabled is true in values.yaml, for nightly we will override this value in the pipeline as we no longer want it running in nightly
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/901

901 Disable initializer for nightly env

---

.github/workflows/merge.yml
.github/workflows/pr.yml
.github/workflows/release.yml

- Uppdated action secret GCR_KEY reference to GCR_CREDENTIALS_JSON used across all repositories instead of the old secret GCR_KEY.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/937

937 update deprecated action secret GCR_KEY

---

.github/workflows/merge.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Makefile
quick-deployment4tests.md

- Change any pipelines to push to the new Artifact Registry
- Change any pipelines / packages that pull images to use the new Artifact Registry
- Change Auth to GCP pipeline command to use V2 as V0 is deprecated
Issue:
- https://github.com/SecureApiGateway/SecureApiGateway/issues/987
- https://github.com/SecureApiGateway/SecureApiGateway/issues/1202

987: Artifact Registry Migration

---

config/defaults/secure-open-banking/oauth2provider-update.json

Adding supportedAuthorizationResponseSigningAlgorithms configuration for the OAuth2.0 Provider to control the signing algorithms supported for signing JARM responses. Setting this to PS256 as this is FAPI compliant.
Without this configuration, then the default signing alg of RS256 is used which is not FAPI compliant.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1275

1275: Configuring the OAuth2.0 Provider supportedAuthorizationResponseSigningAlgorithms

---

main.go
pkg/securebanking/oauth2.go

We want to support the OB Test Directory in both core and OB deployments.
For core, this means we can use OB certs when registering TPPs which is much simpler to configure than using certs issued by the Test Trusted Directory.
Removing OBRI directory software publisher as the OBRI deployment no longer exists.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1338

1338: Supporting OB Test Directory in a core deployment

---

config/defaults/secure-open-banking/managed-objects/apiClient.json

The ApiClient.id field is confusing, it is not the unique id of an ApiClient object, the _id field should be used for this purpose.
The field actually represents the softwareId (which is not unique, multiple clients may be registered for the same piece of software).
In this change we are "renaming" the id field in a non breaking fashion by doing the following:
- Adding new field: `softwareId` which is optional
- Making the existing `id` field optional.
- Adding an onRead script which defaults the `softwareId` field to the `id` value 
Using the script prevents this from being a breaking change by providing a default value for the softwareId.
This change can be applied prior to deploying a code change that uses the softwareId field. …

1529: Rename ApiClient.id field to softwareId

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml

Update TRUSTEDDIR_FQDN > TEST_DIRECTORY_FQDN as part of standardization during the kustoimize > helm epic
Issue:  https://github.com/SecureApiGateway/SecureApiGateway/issues/1679

1679: Migrate IG Components to Helm

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml
pkg/securebanking/oauth2.go

No need for full OB Vs Core split for source of configmap and secrets
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1676

1676: Split IG into AS/RS and deploy to Devenvs

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml
config/defaults/secure-open-banking/cors-login-ui.json

Set the environment variable IDENTITY_AMREALM which is usually set to alpha by default, based off the value in AM_REALM in the fapi-pep-as configmap
This will allow us to overwrite the default alpha and create the realm fapi in our test, this can be merged and stay in place as we've previously discussed using bravo realm for core|ob split like we do in AIC 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1700

1700: Can we create a FAPI Realm

---

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml

Wrong Env Variable moved to FIDC only section, and get the project name from the correct configmap
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1697

1697: Setup New AS/RS Split in ITSS
