am/alpha.go, am/find.go, am/find_test.go, am/oauth2.go, am/policy.go, am/serviceaccount.go
There is common login in the code that looks at an AmResult object for a specific name or ID.
I have implemented a lightweight strategy pattern to perform the search which will reduce much of the repeated code.
=> refactor common find function

.github/workflows/merge.yml, .github/workflows/pr.yml, Makefile
Implement merge and pr actions for the initialiser that will run unit tests and push an image to the dev repo.
=> implement github actions

.github/workflows/merge.yml
When the initializer is merged to master, push to both release and develop repository
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/25
=> apply docker push to both dev and release repo

am/oauth2-test.json, am/oauth2.go, am/oauth2_test.go, am/serviceaccount.go, config/defaults/oauth2provider.json, go.mod, main.go, quick-deployment4tests.md
- New Software Publisher (test-publisher HS256) added
- Fix IG service user password
- Create quick deployment 4 test readme file
- Added the proper tests for the new ammends.
- [Issue 2 functional tests](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests/issues/2)
=> 2: Functional tests fixes

.github/workflows/merge.yml, Makefile
Fix merge action to run the correct target and push the latest image to dev and release.
=> fix merge action

am/oauth2.go, config/defaults/managed-objects/openbanking/accountAccessIntent.json, config/defaults/managed-objects/openbanking/apiClient.json, config/defaults/managed-objects/openbanking/apiClientOrg.json, config/defaults/managed-objects/openbanking/domesticPaymentIntent.json
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/79
=> 79: IAM config issues via initialiser

_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/cronjob.yaml, am/oauth2.go, am/policy_test.go, config/defaults/am-authentication-config/ca.json, config/defaults/am-authentication-config/sca.json, config/defaults/pisp-policy.json
fix the remaining config issues from https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/82
=> fix config issues

config/defaults/ig-oauth2-client.json
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/105
=> 105: Add required scope trusted_gateway for IG route enforcement

config/defaults/oauth2provider.json
- Disable require Software Statement for dynamic client registration on IAM
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/202
=> 202: IAM configuration - Dynamic Registration

.gitignore, am/alpha.go, am/alpha_test.go, am/client.go, am/idm.go, am/oauth2.go, am/policy.go, am/serviceaccount.go, am/system_clients.go, common/error.go, mocks/am/RestReaderWriter.go, platform/authenticate.go
- Added check on errors to skip raise it when 404 is returned.
=> 217: CDK service users initialisation fix

am/alpha.go, am/client.go, am/oauth2.go, am/policy.go, am/serviceaccount.go, am/system_clients.go, common/error.go, platform/authenticate.go
- Change error handling to skip raise and error when 404 is returned
=> 217: cdk user initialisation fix

.gitignore, am/serviceaccount.go, common/model.go, main.go
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/224
=> Create PSU in pipeline

config/defaults/secure-open-banking/policy-evaluation-script.js
- Added improvements in policy-evaluation-script to check properly the permissions values
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/236
=> 236: Register client, create consent

config/defaults/secure-open-banking/policy-evaluation-script.js
- Added responseAttribute 'userResourceOwner'
- Added filter in URI to obtain the managed objects with the ref properties as user and apiClient
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/240
=> 240: AISP evaluation policy script

config/viper/viper-default-configuration.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/252
=> 252: Add new namespace Joyce Gilding

config/defaults/secure-open-banking/policy-evaluation-script.js
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/246
1. In the securebanking-openbanking-demo repository, in the routes implementing the domestic payments, we use the PolicyEnforcementFilter that can parse data to the policy script using the environment object. Thus, in the environment configuration, I have added the "request_method" property representing the method of the request. 
```
"environment": {
"request_method" : ["${request.method}"]
},
```
The implementation is in the PR: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/pull/107
2. In the policy evaluation script, I am getting the "request_method" property from the environment object. Using the switch statment, I made a different case for POST and GET methods. 
- …
=> 246: Scripted policy updates for GET requests on payments flows

config/viper/viper-default-configuration.yaml
remove joyce from viper-default-configuration.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
=> remove joyce from viper-default-configuration.yaml

config/defaults/secure-open-banking/managed-objects/domesticScheduledPaymentIntent.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/312
=> 312: Add accountId in the Domestic Scheduled Payment Intent

_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/configmap.yaml, _infra/helm/securebanking-openbanking-uk-iam-initializer/templates/configmap.yaml
Removed ununsed variables in configmap
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/294
=> Removed ununsed variables in configmap

config/defaults/secure-open-banking/managed-objects/domesticStandingOrderPaymentIntent.json
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/342
=> 342: Replace forgotten 'scheduled' word in the Domestic Standing Order Payment Intent

config/defaults/secure-open-banking/policy-evaluation-script.js
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/329
=> 329: Upgrade policy evaluation script to support domestic standing order

.github/workflows/pr.yml, .github/workflows/release.yml, README.md
- Added release workflow to push the latest image to release gcr
- Modified master workflow to build and push the latest image to develop gcr
- Modified pr workflow to build and push the pr-number image to develop gcr
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/292
=> 292: github action pr number image tagged

config/defaults/secure-open-banking/managed-objects/internationalPaymentIntent.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/358
=> 358: Create International payment intent IDM object

config/defaults/secure-open-banking/policy-evaluation-script.js
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/366
=> 366: Update policy evaluation script to support international payments

README.md, config/defaults/identity-platform/realm-template.json, config/defaults/secure-open-banking/policy-evaluation-script.js, config/viper/viper-default-configuration.yaml, main.go, pkg/common/environment.go, pkg/httprest/utils.go, pkg/identity-platform/authenticate.go, pkg/identity-platform/platform.go, pkg/identity-platform/platform_test.go, pkg/identity-platform/system_clients.go, pkg/securebanking/authentication_config.go, pkg/securebanking/oauth2.go, pkg/securebanking/policy.go, pkg/types/constants.go, pkg/types/exports.go
- Updated all classes to  use the realm from config
- Updated all paths rest calls to use the realm from config
- Updated readme file
- Created new realm template file with realm placeholder
- Updated policy script with placeholder for the realm from config
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/348
=> 348: fix alpha realm hardcoded

config/defaults/secure-open-banking/managed-objects/domesticPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/domesticScheduledPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/domesticStandingOrderIntent.json, config/defaults/secure-open-banking/managed-objects/internationalPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/internationalScheduledPaymentIntent.json
Issues:
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/310
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/438
=> 438, 310: Update payment intents

config/defaults/secure-open-banking/managed-objects/domesticPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/domesticScheduledPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/domesticStandingOrderIntent.json, config/defaults/secure-open-banking/managed-objects/internationalPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/internationalScheduledPaymentIntent.json
Upgrade IDM objects to support the calculated response elements
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/439
=> Adding final charge object to all the intent items.

config/defaults/secure-open-banking/managed-objects/domesticPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/domesticScheduledPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/domesticStandingOrderIntent.json, config/defaults/secure-open-banking/managed-objects/internationalPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/internationalScheduledPaymentIntent.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/455
=> 455: Review the Domestic Payment Intent Schema

config/defaults/secure-open-banking/managed-objects/internationalPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/internationalScheduledPaymentIntent.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/457
=> 457: ExchangeRateInformation from Data is missing

config/defaults/secure-open-banking/managed-objects/internationalPaymentIntent.json, config/defaults/secure-open-banking/managed-objects/internationalScheduledPaymentIntent.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/483
=> 483: ExchangeRate should have number type in IDM

config/defaults/secure-open-banking/managed-objects/internationalStandingOrderIntent.json
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/460
=> 460: Create international standing order intent IDM object

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml, _infra/helm/securebanking-openbanking-uk-iam-initializer/values.yaml
Fixing cronjob.yaml image tag value to match deployment.imageOverride.tag as per the values file
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
=> 276: Fixing cronjob.yaml image tag value

config/defaults/secure-open-banking/managed-objects/domesticStandingOrdersIntent.json, config/defaults/secure-open-banking/managed-objects/internationalStandingOrdersIntent.json, config/defaults/secure-open-banking/policy-evaluation-script.js
- Standing orders IMD json-based renamed
- Policy script updated
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/533
=> 533: rename IDM standing orders intent

config/defaults/secure-open-banking/managed-objects/filePaymentsIntent.json
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/544
Description: Created the File Payment intent IDM object.
=> 544: Create File Payment intent IDM object

config/defaults/secure-open-banking/policy-evaluation-script.js
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/554
Description: Updated policy evaluation script to support file payment.
=> 554: Updating policy evaluation script

.github/workflows/pr.yml
'-' is not a valid character in a value
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/276
=> 276: Fix broken initialize-sbat-namespaces pipelines

.github/workflows/pr.yml
Pass ARGO_VALUES_PREFIX
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/276
=> 276: Fix failure to deploy PR docker image via argo

config/defaults/secure-open-banking/oauth2provider-update.json
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/632
=> 632: Removing device_code and token OAuth2 response_types

config/defaults/secure-open-banking/oauth2provider-update.json, pkg/securebanking/oauth2.go, pkg/types/oauth2models.go
As part of AM 7.2.0, the OAuth2Provider config json structure has been changed to move several configuration options into a new "pluginsConfig" block.
Updating initializer code and config to use the new structure.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/437
=> 437: AM 7.2.0 compatibility

config/defaults/secure-open-banking/managed-objects/domesticVrpPaymentIntent.json
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/628
Description: Created the Domestic VRP Payment intent IDM object.
=> 628: Create Domestic VRP Payment intent IDM object

config/defaults/secure-open-banking/policy-evaluation-script.js
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/640
Description: Updated policy evaluation script to support domestic vrp payment.
=> 640: Updating policy evaluation script

config/defaults/secure-open-banking/managed-objects/domesticVrpPaymentIntent.json
- Fix controlParameter array of objects to populate properly the sibling objects
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/628
=> 628: VRP payment managed object intent

config/defaults/secure-open-banking/managed-objects/domesticVrpPaymentIntent.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/628
Description: Fixing domestic vrp intent idm object according to version 3.1.10 spec.
=> 628: Fix domestic vrp intent idm object

config/defaults/secure-open-banking/pisp-policy.json, config/defaults/secure-open-banking/policy-evaluation-script.js
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/695
- Added endpoints fro VRPs to the PISP policy
- Fixed incorrect VRPs paths defined in the policy evaluation script.
=> Update policy requirements for VRPs

config/defaults/secure-open-banking/oauth2provider-update.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/697
=> 697: Adding public to supportedSubjectTypes AM OAuth2 config

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
Incorrect values used for the secret user and password, correct values added in 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/304
=> 304 - Fix nightly build

config/defaults/auth-helper/FidcDismiss2FA.json, config/viper/viper-default-configuration.yaml, main.go, pkg/identity-platform/authenticate.go, pkg/types/configuration.go
Trying to make the initializer authenticate with FIdC
Issue: https://github.com/secureapigateway/secureapigateway/issues/304
=> 304: Use FIDC specific auth URI

pkg/securebanking/oauth2.go
See related Gateway PR: https://github.com/SecureApiGateway/securebanking-openbanking-uk-gateway/pull/301
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/793
=> 793: Configure AM Remote Consent to call RCS via IG

README.md
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/797
=> 797: Removing defunct environment variables from README

config/defaults/secure-open-banking/managed-objects/apiClient.json
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/865
=> 865: Add jwks and roles to the ApiClient object definition

config/defaults/secure-open-banking/policy-evaluation-script.js
Using encodeURI js function to make sure URIs are encoded properly in the OB policy script
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/911
=> 911: Fix URI encoding in OB policy script

_infra/helm/securebanking-openbanking-uk-iam-initializer/Chart.yaml, _infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
Issue: https://github.com/secureapigateway/secureapigateway/issues/851
=> 851: Make the fidc-configurator use deployment-config

config/defaults/secure-open-banking/policy-evaluation-script.js
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/940
Description: Removed the initiationMatch & deepCompare logic.
=> 940: Policy evaluation script cleanup

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1161
=> 1161: Add in App & Chart Label

.github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1220
=> 1220: Fix workflow for dependabot

.github/workflows/merge.yml, .github/workflows/pr.yml, .github/workflows/release.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264
=> 1264 deprecated actions

pkg/securebanking/idm.go
HTTP PATCH is being used to add to the set of defined managed objects. Note: PUT could be used instead but we would need to PUT the complete set of definitions (including all of the defs that already exists and come as standard).
We have observed that sometimes one of the definitions is missing from IDM, even though a 200 response was received, this appears to be a race condition. Combining all json patches into a single json array so that the operations are applied in a single request.
We will need to continue observing our development environment and investigate further if the problem is not resolved by this change.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1297
=> 1297: Combining managed object patch operations into single request

main.go, pkg/securebanking/idm.go
Need the managed objects, so remove if statement and rename to SAPIG instead of OB
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1319
=> 1319: Change FIDC code for new SAPIGTYPE

README.md, _infra/helm/securebanking-openbanking-uk-iam-initializer/readme.md, _infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml, _infra/helm/securebanking-openbanking-uk-iam-initializer/values.yaml, main.go, pkg/identity-platform/authenticate.go, pkg/identity-platform/platform.go, pkg/securebanking/google_secret_stores.go, pkg/types/configuration.go
- Update config reference to cloudType
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1368
=> 1368: Improve FIDC secret templates and standardise config for cloudType

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml, config/viper/viper-default-configuration.yaml
- Fix viper defaults to look for CLOUDTYPE
- Get SAPIGTYPR from configmap
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1373
=> 1373: Investigate deploy issues with FIDC 

.github/workflows/merge.yml, .github/workflows/pr-helm.yml, .github/workflows/pr.yml, .github/workflows/slackNotification.yml, Makefile
Amend PR Slack Notify & Merge workflow to use steps in CI Repo
Standardise workflows in the process of doing this
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389
=> 1389: Use CI Repo for standardised steps in github workflows

_infra/helm/securebanking-openbanking-uk-iam-initializer/Chart.yaml
Update Helm Version to 3.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
=> 1404: Create and Release SAPIG Core and OB

_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml, pkg/securebanking/oauth2.go, pkg/types/configuration.go
Create new env var from the value of TRUSTEDDIR_FQDN
New Go variable from the above env var for the new test trusted directory FQDN
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/846
=> 846: Create DNS for new stand alone test trusted directory and update relevant configs

_infra/helm/securebanking-openbanking-uk-iam-initializer/Chart.yaml
Update Helm Version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1476
=> 1476: Build and Deploy SAPIG 3.1.0 to relenv

_infra/helm/securebanking-openbanking-uk-iam-initializer/Chart.yaml
Bump helm version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1516
=> 1516: Create release 3.2.0 and deploy

_infra/helm/securebanking-openbanking-uk-iam-initializer/Chart.yaml
Bump helm version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602
=> 1602: Build and Deploy SAPIG 4.0.0

_infra/helm/securebanking-openbanking-uk-iam-initializer/readme.md, _infra/helm/securebanking-openbanking-uk-iam-initializer/templates/job.yaml, config/defaults/secure-open-banking/cors-login-ui.json, config/defaults/secure-open-banking/create-base-url-source.json, config/defaults/secure-open-banking/create-validation-service.json, config/defaults/secure-open-banking/oauth2provider-core-update.json, config/defaults/secure-open-banking/oauth2provider-update.json, config/viper/viper-default-configuration.yaml, pkg/securebanking/oauth2.go, pkg/types/configuration.go
Update config for new IG AS / RS split, use old configmaps if the sapig type is OB
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1676
=> 1676: Split IG into AS/RS and deploy to Devenvs

_infra/helm/securebanking-openbanking-uk-iam-initializer/Chart.yaml
Bump helm version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1703
=> 1703: Create SAPIG 5.0.0
